---
title: "`r read.dcf('DESCRIPTION', fields = 'Package')[1]`"  
author: "`r rworkflows::use_badges()`" 
date: "<h4>README updated: <i>`r format( Sys.Date(), '%b-%d-%Y')`</i></h4>"
output:
  github_document
---

```{r, echo=FALSE, include=FALSE}
pkg <- read.dcf("DESCRIPTION", fields = "Package")[1]
title <- gsub("\n"," ",read.dcf("DESCRIPTION", fields = "Title")[1])
description <- gsub("\n"," ",read.dcf("DESCRIPTION", fields = "Description")[1])
URL <- read.dcf('DESCRIPTION', fields = 'URL')[1]
owner <- strsplit(URL,"/")[[1]][4]
repo <- strsplit(URL,"/")[[1]][5]
```

## ``r pkg``: `r gsub("\n","",title)`

### `r gsub("\n","",description)`
 
<!-- If you use ``r pkg``, please cite:  -->

<!-- > `r utils::citation(pkg)$textVersion` -->

## Installation 

```R
if(!require("remotes")) install.packages("remotes")

remotes::install_github("`r paste(owner,repo,sep='/')`")
library(`r pkg`)
```
## Documentation 

### [Website](https://`r owner`.github.io/`r repo`) 
### [Getting started](https://`r owner`.github.io/`r repo`/articles/`r pkg`) 

<hr>

## Session Info

<details>
```{r}
utils::sessionInfo()
```
</details>

