#' Pipe operator
#'
#' See \code{magrittr::\link[magrittr:pipe]{\%>\%}} for details.
#' 
#' Generated by \code{\link[usethis]{use_pipe}}. Modified to import from
#' \code{dplyr} instead of \code{magrittr}.
#'
#' @name %>%
#' @rdname pipe
#' @keywords internal
#' @export
#' @importFrom dplyr %>%
#' @usage lhs \%>\% rhs
#' @param lhs A value or the magrittr placeholder.
#' @param rhs A function call using the magrittr semantics.
#' 
#' @examples
#' seq_len(10) %>% sum
#' 
#' @return The result of calling `rhs(lhs)`.
#' 
#' @keywords internal
NULL
